In [89]:
import nltk  #importing natural language tool kit

In [90]:
from nltk.corpus import stopwords #importing the stopwords from nltk

In [91]:
nltk.download('punkt') #downloading the needed punkt package

[nltk_data] Downloading package punkt to
[nltk_data]     /Users/rakshitmalhotra/nltk_data...
[nltk_data]   Package punkt is already up-to-date!


True

In [92]:
nltk.download('stopwords') #downloading the needed stopwords package

[nltk_data] Downloading package stopwords to
[nltk_data]     /Users/rakshitmalhotra/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


True

In [93]:
import glob #importing glob

In [365]:
import math #importing math and all its avaliable inbuilt functionalities with *
from math import *
line=''
wordlist=list()
s=set()
path='Folders/Assessment1/*.txt'
flist=glob.glob(path) #reading the list of needed files

In [366]:
print(flist)


['Folders/Assessment1/asses-1-text3.txt', 'Folders/Assessment1/asses-1-text2.txt', 'Folders/Assessment1/asses-1-text1.txt', 'Folders/Assessment1/asses-1-text4.txt']


In [367]:
for fname in flist:  
    tfile=open(fname,"r") 
    line=tfile.read().strip() 
    line=line.lower() 
    tfile.close()
    s=s.union(set(line.split(' '))) 
    wordlist.append(list(line.split(' '))) 
print(wordlist)
print("\n\n")
s=sorted(s) 
print(s) 

[['hello', 'my', 'name', 'is', 'ray', 'saksham', 'khan', '.', 'i', 'am', 'from', 'jalandhar', '.', 'i', 'study', 'in', 'vit', '.', 'my', 'favourite', 'programming', 'language', 'is', 'java', '.', 'i', 'use', 'java', 'for', 'data', 'science', 'as', 'well', 'as', 'for', 'web', 'development', '.', 'i', 'am', 'a', 'board', 'member', 'at', 'csi-vit', '.'], ['hello', 'my', 'name', 'is', 'adit', 'kumar', '.', 'i', 'am', 'from', 'jammu', 'and', 'kashmir', '.', 'i', 'study', 'in', 'vit', '.', 'my', 'favourite', 'programming', 'language', 'is', 'c++', '.', 'my', 'family', 'belongs', 'to', 'khyber', 'district', 'of', 'pakistan', '.', 'i', 'love', 'to', 'eat', 'and', 'sleep', 'a', 'lot', 'and', 'hence', 'my', 'pet', 'name', 'is', 'panda'], ['hello', 'my', 'name', 'is', 'rakshit', '.', 'i', 'am', 'from', 'delhi', '.', 'i', 'study', 'in', 'vit', '.', 'my', 'favourite', 'programming', 'language', 'is', 'python', '.', 'i', 'use', 'python', 'for', 'data', 'science', 'as', 'well', 'as', 'for', 'web', 'd

In [97]:
st=set(stopwords.words('english')) #set of stopwords of enlgish

## STOPWORDS REMOVAL

In [98]:
import string #importing string
l=list() #making a new list
for x in s: 
    if x.lower() not in st and x not in string.punctuation:
        l.append(x)
print(l)

['adit', 'batsman', 'belong', 'belongs', 'best', 'board', 'c++', 'captain', 'cricket', 'cricketers', 'csi-vit', 'data', 'delhi', 'development', 'district', 'eat', 'family', 'favourite', 'former', 'hard', 'hello', 'hence', 'indian', 'jalandhar', 'jammu', 'java', 'kashmir', 'khan', 'khyber', 'kohli', 'kumar', 'language', 'lot', 'love', 'many', 'matches', 'member', 'name', 'pakistan', 'panda', 'pet', 'programming', 'python', 'rakshit', 'rated', 'ray', 'saksham', 'science', 'sleep', 'study', 'team', 'use', 'virat', 'vit', 'web', 'well', 'win', 'work', 'world']


In [99]:
i=0
ct=0
tf_line=''
doc_counts=[]
for term in l:
    doc_counts.append(0)
    for fdoc in flist:
        doc=open(fdoc)
        line=doc.read().lower()
        doc.close()
        #print(line)
        ct=line.count(str(term))
        tf_line+=str(ct)+','
        if(ct>0):
            doc_counts[i]+=1
    i+=1
    tf_line= tf_line.strip()+'\n'
print(tf_line)

0,1,0,0,
0,0,0,1,
0,1,0,1,
0,1,0,0,
0,0,0,1,
1,0,0,0,
0,1,0,0,
0,0,0,1,
0,0,0,2,
0,0,0,1,
1,0,0,0,
1,0,1,0,
0,0,1,1,
1,0,1,0,
0,1,0,0,
0,1,0,0,
0,1,0,0,
1,1,1,0,
0,0,0,1,
0,0,0,1,
1,1,1,1,
0,1,0,0,
0,0,0,1,
1,0,0,0,
0,1,0,0,
2,0,0,0,
0,1,0,0,
1,0,0,0,
0,1,0,0,
0,0,0,1,
0,1,0,0,
1,1,1,0,
0,1,0,0,
0,1,0,1,
0,0,0,1,
0,0,0,1,
1,0,0,0,
1,2,1,1,
0,1,0,0,
0,1,0,0,
0,1,0,0,
1,1,1,0,
0,0,2,0,
0,0,1,0,
0,0,0,1,
1,0,0,0,
1,0,0,0,
1,0,1,0,
0,1,0,0,
1,1,1,0,
0,0,0,1,
1,0,1,0,
0,0,0,1,
2,1,1,0,
1,0,1,0,
1,0,1,0,
0,0,0,1,
0,0,0,1,
0,0,0,1,



# STEMMING

In [100]:
from nltk.stem import LancasterStemmer
ls=LancasterStemmer()
stem=list()
for word in l:
    if ls.stem(word) not in stem:
        stem.append(word)
        print(ls.stem(word))

adit
batsm
belong
best
board
c++
captain
cricket
csi-vit
dat
delh
develop
district
eat
famy
favourit
form
hard
hello
hent
ind
jalandh
jammu
jav
kashmir
khan
khyb
kohl
kum
langu
lot
lov
many
match
memb
nam
pak
pand
pet
program
python
rakshit
rat
ray
saksham
sci
sleep
study
team
us
vir
vit
web
wel
win
work
world


In [101]:
j=0
count=0
tf_line_1=list()
doc_counts_1=[]

for term in stem:
    doc_counts_1.append(0)
    temp=list()
    for fdoc in flist:
        doc=open(fdoc)
        line=doc.read().lower()
        doc.close()
        #print(line)
        count=line.count(str(term))
        temp.append(count)
        if(count>0):
            doc_counts_1[j]+=1
    tf_line_1.append(temp)            
    print(tf_line_1[j])
    j+=1

[0, 1, 0, 0]
[0, 0, 0, 1]
[0, 1, 0, 1]
[0, 0, 0, 1]
[1, 0, 0, 0]
[0, 1, 0, 0]
[0, 0, 0, 1]
[0, 0, 0, 2]
[1, 0, 0, 0]
[1, 0, 1, 0]
[0, 0, 1, 1]
[1, 0, 1, 0]
[0, 1, 0, 0]
[0, 1, 0, 0]
[0, 1, 0, 0]
[1, 1, 1, 0]
[0, 0, 0, 1]
[0, 0, 0, 1]
[1, 1, 1, 1]
[0, 1, 0, 0]
[0, 0, 0, 1]
[1, 0, 0, 0]
[0, 1, 0, 0]
[2, 0, 0, 0]
[0, 1, 0, 0]
[1, 0, 0, 0]
[0, 1, 0, 0]
[0, 0, 0, 1]
[0, 1, 0, 0]
[1, 1, 1, 0]
[0, 1, 0, 0]
[0, 1, 0, 1]
[0, 0, 0, 1]
[0, 0, 0, 1]
[1, 0, 0, 0]
[1, 2, 1, 1]
[0, 1, 0, 0]
[0, 1, 0, 0]
[0, 1, 0, 0]
[1, 1, 1, 0]
[0, 0, 2, 0]
[0, 0, 1, 0]
[0, 0, 0, 1]
[1, 0, 0, 0]
[1, 0, 0, 0]
[1, 0, 1, 0]
[0, 1, 0, 0]
[1, 1, 1, 0]
[0, 0, 0, 1]
[1, 0, 1, 0]
[0, 0, 0, 1]
[2, 1, 1, 0]
[1, 0, 1, 0]
[1, 0, 1, 0]
[0, 0, 0, 1]
[0, 0, 0, 1]
[0, 0, 0, 1]


In [102]:
print(doc_counts_1)
        

[1, 1, 2, 1, 1, 1, 1, 1, 1, 2, 2, 2, 1, 1, 1, 3, 1, 1, 4, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 3, 1, 2, 1, 1, 1, 4, 1, 1, 1, 3, 1, 1, 1, 1, 1, 2, 1, 3, 1, 2, 1, 3, 2, 2, 1, 1, 1]


In [275]:
idf=list()
for i in doc_counts_1:
    idf_cal=math.log((1+len(flist))/i)
    idf.append(idf_cal)


In [276]:
idf

[1.6094379124341003,
 1.6094379124341003,
 0.9162907318741551,
 1.6094379124341003,
 1.6094379124341003,
 1.6094379124341003,
 1.6094379124341003,
 1.6094379124341003,
 1.6094379124341003,
 0.9162907318741551,
 0.9162907318741551,
 0.9162907318741551,
 1.6094379124341003,
 1.6094379124341003,
 1.6094379124341003,
 0.5108256237659907,
 1.6094379124341003,
 1.6094379124341003,
 0.22314355131420976,
 1.6094379124341003,
 1.6094379124341003,
 1.6094379124341003,
 1.6094379124341003,
 1.6094379124341003,
 1.6094379124341003,
 1.6094379124341003,
 1.6094379124341003,
 1.6094379124341003,
 1.6094379124341003,
 0.5108256237659907,
 1.6094379124341003,
 0.9162907318741551,
 1.6094379124341003,
 1.6094379124341003,
 1.6094379124341003,
 0.22314355131420976,
 1.6094379124341003,
 1.6094379124341003,
 1.6094379124341003,
 0.5108256237659907,
 1.6094379124341003,
 1.6094379124341003,
 1.6094379124341003,
 1.6094379124341003,
 1.6094379124341003,
 0.9162907318741551,
 1.6094379124341003,
 0.51082562

In [277]:
(tf_line_1)

[[0, 1, 0, 0],
 [0, 0, 0, 1],
 [0, 1, 0, 1],
 [0, 0, 0, 1],
 [1, 0, 0, 0],
 [0, 1, 0, 0],
 [0, 0, 0, 1],
 [0, 0, 0, 2],
 [1, 0, 0, 0],
 [1, 0, 1, 0],
 [0, 0, 1, 1],
 [1, 0, 1, 0],
 [0, 1, 0, 0],
 [0, 1, 0, 0],
 [0, 1, 0, 0],
 [1, 1, 1, 0],
 [0, 0, 0, 1],
 [0, 0, 0, 1],
 [1, 1, 1, 1],
 [0, 1, 0, 0],
 [0, 0, 0, 1],
 [1, 0, 0, 0],
 [0, 1, 0, 0],
 [2, 0, 0, 0],
 [0, 1, 0, 0],
 [1, 0, 0, 0],
 [0, 1, 0, 0],
 [0, 0, 0, 1],
 [0, 1, 0, 0],
 [1, 1, 1, 0],
 [0, 1, 0, 0],
 [0, 1, 0, 1],
 [0, 0, 0, 1],
 [0, 0, 0, 1],
 [1, 0, 0, 0],
 [1, 2, 1, 1],
 [0, 1, 0, 0],
 [0, 1, 0, 0],
 [0, 1, 0, 0],
 [1, 1, 1, 0],
 [0, 0, 2, 0],
 [0, 0, 1, 0],
 [0, 0, 0, 1],
 [1, 0, 0, 0],
 [1, 0, 0, 0],
 [1, 0, 1, 0],
 [0, 1, 0, 0],
 [1, 1, 1, 0],
 [0, 0, 0, 1],
 [1, 0, 1, 0],
 [0, 0, 0, 1],
 [2, 1, 1, 0],
 [1, 0, 1, 0],
 [1, 0, 1, 0],
 [0, 0, 0, 1],
 [0, 0, 0, 1],
 [0, 0, 0, 1]]

In [278]:
div=list()
for i in range(0,len(wordlist)):
    div.append(len(wordlist[i]))
    

In [279]:
div

[46, 50, 37, 45]

In [280]:
divid=list()
for i in tf_line_1:
    new=list()
    for j in range(0,len(flist)):
        calci=i[j]/div[j]
        new.append(calci)
    divid.append(new)
    print(new)    

[0.0, 0.02, 0.0, 0.0]
[0.0, 0.0, 0.0, 0.022222222222222223]
[0.0, 0.02, 0.0, 0.022222222222222223]
[0.0, 0.0, 0.0, 0.022222222222222223]
[0.021739130434782608, 0.0, 0.0, 0.0]
[0.0, 0.02, 0.0, 0.0]
[0.0, 0.0, 0.0, 0.022222222222222223]
[0.0, 0.0, 0.0, 0.044444444444444446]
[0.021739130434782608, 0.0, 0.0, 0.0]
[0.021739130434782608, 0.0, 0.02702702702702703, 0.0]
[0.0, 0.0, 0.02702702702702703, 0.022222222222222223]
[0.021739130434782608, 0.0, 0.02702702702702703, 0.0]
[0.0, 0.02, 0.0, 0.0]
[0.0, 0.02, 0.0, 0.0]
[0.0, 0.02, 0.0, 0.0]
[0.021739130434782608, 0.02, 0.02702702702702703, 0.0]
[0.0, 0.0, 0.0, 0.022222222222222223]
[0.0, 0.0, 0.0, 0.022222222222222223]
[0.021739130434782608, 0.02, 0.02702702702702703, 0.022222222222222223]
[0.0, 0.02, 0.0, 0.0]
[0.0, 0.0, 0.0, 0.022222222222222223]
[0.021739130434782608, 0.0, 0.0, 0.0]
[0.0, 0.02, 0.0, 0.0]
[0.043478260869565216, 0.0, 0.0, 0.0]
[0.0, 0.02, 0.0, 0.0]
[0.021739130434782608, 0.0, 0.0, 0.0]
[0.0, 0.02, 0.0, 0.0]
[0.0, 0.0, 0.0, 0.

# CALCULATING TF-IDF

In [281]:
import numpy as np
tfidf=list()
for i in range(0,len(divid)):
    tfidf.append(np.asarray(divid[i])*idf[i]) #USING NUMPY AS LIST CAN'T BE MULTIPLIED WITH FLOAT

In [282]:
len(new)
for i in tfidf:
    print(i)

[0.         0.03218876 0.         0.        ]
[0.         0.         0.         0.03576529]
[0.         0.01832581 0.         0.02036202]
[0.         0.         0.         0.03576529]
[0.03498778 0.         0.         0.        ]
[0.         0.03218876 0.         0.        ]
[0.         0.         0.         0.03576529]
[0.         0.         0.         0.07153057]
[0.03498778 0.         0.         0.        ]
[0.01991936 0.         0.02476461 0.        ]
[0.         0.         0.02476461 0.02036202]
[0.01991936 0.         0.02476461 0.        ]
[0.         0.03218876 0.         0.        ]
[0.         0.03218876 0.         0.        ]
[0.         0.03218876 0.         0.        ]
[0.0111049  0.01021651 0.0138061  0.        ]
[0.         0.         0.         0.03576529]
[0.         0.         0.         0.03576529]
[0.00485095 0.00446287 0.00603091 0.00495875]
[0.         0.03218876 0.         0.        ]
[0.         0.         0.         0.03576529]
[0.03498778 0.         0.         

In [283]:
divid

[[0.0, 0.02, 0.0, 0.0],
 [0.0, 0.0, 0.0, 0.022222222222222223],
 [0.0, 0.02, 0.0, 0.022222222222222223],
 [0.0, 0.0, 0.0, 0.022222222222222223],
 [0.021739130434782608, 0.0, 0.0, 0.0],
 [0.0, 0.02, 0.0, 0.0],
 [0.0, 0.0, 0.0, 0.022222222222222223],
 [0.0, 0.0, 0.0, 0.044444444444444446],
 [0.021739130434782608, 0.0, 0.0, 0.0],
 [0.021739130434782608, 0.0, 0.02702702702702703, 0.0],
 [0.0, 0.0, 0.02702702702702703, 0.022222222222222223],
 [0.021739130434782608, 0.0, 0.02702702702702703, 0.0],
 [0.0, 0.02, 0.0, 0.0],
 [0.0, 0.02, 0.0, 0.0],
 [0.0, 0.02, 0.0, 0.0],
 [0.021739130434782608, 0.02, 0.02702702702702703, 0.0],
 [0.0, 0.0, 0.0, 0.022222222222222223],
 [0.0, 0.0, 0.0, 0.022222222222222223],
 [0.021739130434782608, 0.02, 0.02702702702702703, 0.022222222222222223],
 [0.0, 0.02, 0.0, 0.0],
 [0.0, 0.0, 0.0, 0.022222222222222223],
 [0.021739130434782608, 0.0, 0.0, 0.0],
 [0.0, 0.02, 0.0, 0.0],
 [0.043478260869565216, 0.0, 0.0, 0.0],
 [0.0, 0.02, 0.0, 0.0],
 [0.021739130434782608, 0.0,

In [284]:
tfidf

[array([0.        , 0.03218876, 0.        , 0.        ]),
 array([0.        , 0.        , 0.        , 0.03576529]),
 array([0.        , 0.01832581, 0.        , 0.02036202]),
 array([0.        , 0.        , 0.        , 0.03576529]),
 array([0.03498778, 0.        , 0.        , 0.        ]),
 array([0.        , 0.03218876, 0.        , 0.        ]),
 array([0.        , 0.        , 0.        , 0.03576529]),
 array([0.        , 0.        , 0.        , 0.07153057]),
 array([0.03498778, 0.        , 0.        , 0.        ]),
 array([0.01991936, 0.        , 0.02476461, 0.        ]),
 array([0.        , 0.        , 0.02476461, 0.02036202]),
 array([0.01991936, 0.        , 0.02476461, 0.        ]),
 array([0.        , 0.03218876, 0.        , 0.        ]),
 array([0.        , 0.03218876, 0.        , 0.        ]),
 array([0.        , 0.03218876, 0.        , 0.        ]),
 array([0.0111049 , 0.01021651, 0.0138061 , 0.        ]),
 array([0.        , 0.        , 0.        , 0.03576529]),
 array([0.    

# QUERYING 

In [286]:
query=input()

 hello adit


In [287]:
from nltk.tokenize import word_tokenize

In [288]:
word_tokens=word_tokenize(query)

In [289]:
word_tokens=sorted(word_tokens)

In [290]:
j=0
count=0
tf_line_2=list()
doc_counts_2=[]

for term in word_tokens:
    doc_counts_2.append(0)
    temp=list()
    for fdoc in flist:
        doc=open(fdoc)
        line=doc.read().lower()
        doc.close()
        #print(line)
        count=line.count(str(term))
        temp.append(count)
        if(count>0):
            doc_counts_2[j]+=1
    tf_line_2.append(temp)            
    print(tf_line_2[j])
    j+=1
print(len(tf_line_2))


[0, 1, 0, 0]
[1, 1, 1, 1]
2


In [361]:
def square(list):
    return [i ** 2 for i in list]
cosine_sim=list()
numiter=0
for word in word_tokens:
    for j in range(0,len(stem)):
        tfidfq=list()
        if(word == stem[j]):
            print('\n\n')
            print("THE IDF FOR "+str(word)+" IS "+str(idf[j])+'\n\n')
            #print(tf_line_2[k])
            print('\n\n')
            tfidfq.append(np.array(tf_line_2[numiter])*idf[j])
            print("original tfidf is " + str(tfidf[j]))
            print('\n\n')
            a=(np.sqrt(np.sum(square(tfidfq))))
            b=(np.sqrt(np.sum(square(tfidf[j]))))
            print((np.dot(tfidfq, tfidf[j])))
            print('\n\n')
            print(tfidfq)
            print('\n\n')
            print(tfidf[j])
            print('\n\n')
            something=a*b
            print(something)
            new_arr=(np.multiply(tfidfq,tfidf[j]))
            bottom1=(np.sqrt(np.sum(np.square(tfidfq))))
            bottom2=(np.sqrt(np.sum(np.square(tfidf[j]))))
            multi=bottom1*bottom2
            print(multi)
            array=(np.divide(new_arr,multi))
            order = (-array).argsort()
            order=np.add(order,1)
            print('\n\n')
            print("THE RANKING IS FROM 1 TO 4, WHERE 1 IS REPRESENTS HIGHEST SIMILARITY")
            print('---------------------------------------------')
            print(order) 
            print('---------------------------------------------')

#             for i in range(0,int(tfidf[j])):
#                 if i>0:
#                     print(i)
#                     print("********")
#                     cosine_sim.append(np.dot(tfidfq,i)/(np.sqrt(np.sum(square((tfidfq)))) * np.sqrt(np.sum(i**2))))
#                     # print(k)
#                     # print('------------')
#                     # cosine_sim.append([a*b for a,b in zip(tfidfq,tfidf[j])] /(np.sqrt(np.sum(square((tfidfq)))) * np.sqrt(np.sum(tfidf[j]**2))))
#                     #cosine_sim.append(np.dot(tfidfq, tfidf[j]) /something)
#                     print("-------------------")
            numiter+=1
                




THE IDF FOR adit IS 1.6094379124341003





original tfidf is [0.         0.03218876 0.         0.        ]



[0.05180581]



[array([0.        , 1.60943791, 0.        , 0.        ])]



[0.         0.03218876 0.         0.        ]



0.05180580787960469
0.05180580787960469



THE RANKING IS FROM 1 TO 4, WHERE 1 IS REPRESENTS HIGHEST SIMILARITY
---------------------------------------------
[[2 1 3 4]]
---------------------------------------------



THE IDF FOR hello IS 0.22314355131420976





original tfidf is [0.00485095 0.00446287 0.00603091 0.00495875]



[0.00453059]



[array([0.22314355, 0.22314355, 0.22314355, 0.22314355])]



[0.00485095 0.00446287 0.00603091 0.00495875]



0.004560213433366393
0.004560213433366393



THE RANKING IS FROM 1 TO 4, WHERE 1 IS REPRESENTS HIGHEST SIMILARITY
---------------------------------------------
[[3 4 1 2]]
---------------------------------------------
